import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.jpg" />
      </Head>
      <h1 className="text-5xl font-bold text-[#f54748] text-center">
        Twitter Clone
      </h1>
      <main>
        {/* Sidebar  */}
        {/* Feed */}
        {/* Badgets */}
      </main>
    </div>
  );
}
