import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.jpg" />
      </Head>
      {/* <h1 className="text-5xl font-bold text-[#f54748] text-center bg-black border-b-2 py-5">
        Twitter Clone
      </h1> */}
      <main className="bg-black min-h-screen max-w-[1500px] flex mx-auto">
        {/* Sidebar  */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Badgets */}
        {/* Modal */}
      </main>
    </div>
  );
}
